# Generated by Django 4.2.16 on 2024-12-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0008_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_other_person', 'Może zobaczyć osoby innych właściceli')]},
        ),
    ]
